DROP TABLE IF EXISTS song;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS song_tag;


CREATE TABLE user (
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT UNIQUE NOT NULL,
password TEXT NOT NULL
);

CREATE TABLE song (
id INTEGER PRIMARY KEY AUTOINCREMENT,
creator_id INTEGER NOT NULL,
created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
title TEXT NOT NULL,
author TXET,
body TEXT,
FOREIGN KEY (creator_id) REFERENCES user (id)
);

CREATE TABLE tag (
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL
);

CREATE TABLE song_tag (
song_id INTEGER NOT NULL,
tag_id INTEGER NOT NULL,
FOREIGN KEY (song_id) REFERENCES song (id),
FOREIGN KEY (tag_id) REFERENCES user (id)
);

